{
  Copyright (c) 2020, Vencejo Software
  Distributed under the terms of the Modified BSD License
  The full license is distributed with this software
}
program test;

{$R 'sql.res' '..\resources\sql.rc'}

uses
  RunTest,
  BetweenSQLCondition in '..\..\code\condition\BetweenSQLCondition.pas',
  EqualSQLCondition in '..\..\code\condition\EqualSQLCondition.pas',
  GreaterOrEqualSQLCondition in '..\..\code\condition\GreaterOrEqualSQLCondition.pas',
  GreaterSQLCondition in '..\..\code\condition\GreaterSQLCondition.pas',
  InSQLCondition in '..\..\code\condition\InSQLCondition.pas',
  IsNotNullSQLCondition in '..\..\code\condition\IsNotNullSQLCondition.pas',
  IsNullSQLCondition in '..\..\code\condition\IsNullSQLCondition.pas',
  JoinedSQLCondition in '..\..\code\condition\JoinedSQLCondition.pas',
  LessOrEqualSQLCondition in '..\..\code\condition\LessOrEqualSQLCondition.pas',
  LessSQLCondition in '..\..\code\condition\LessSQLCondition.pas',
  LikeSQLCondition in '..\..\code\condition\LikeSQLCondition.pas',
  NotEqualSQLCondition in '..\..\code\condition\NotEqualSQLCondition.pas',
  SingleSQLCondition in '..\..\code\condition\SingleSQLCondition.pas',
  SQLCondition in '..\..\code\condition\SQLCondition.pas',
  AndNotSQLJoin in '..\..\code\join\AndNotSQLJoin.pas',
  AndSQLJoin in '..\..\code\join\AndSQLJoin.pas',
  NoneSQLJoin in '..\..\code\join\NoneSQLJoin.pas',
  OrNotSQLJoin in '..\..\code\join\OrNotSQLJoin.pas',
  OrSQLJoin in '..\..\code\join\OrSQLJoin.pas',
  SQLJoin in '..\..\code\join\SQLJoin.pas',
  WhereSQL in '..\..\code\join\WhereSQL.pas',
  BooleanSQLParameterValue in '..\..\code\parameter\value\BooleanSQLParameterValue.pas',
  DateSQLParameterValue in '..\..\code\parameter\value\DateSQLParameterValue.pas',
  DateTimeSQLParameterValue in '..\..\code\parameter\value\DateTimeSQLParameterValue.pas',
  ReplaceableSQLParameter in '..\..\code\parameter\ReplaceableSQLParameter.pas',
  ReplaceableSQLParameterValue in '..\..\code\parameter\value\ReplaceableSQLParameterValue.pas',
  ExtendedFormatSetting in '..\..\code\parameter\value\ExtendedFormatSetting.pas',
  ExtendedSQLParameterValue in '..\..\code\parameter\value\ExtendedSQLParameterValue.pas',
  IntegerSQLParameterValue in '..\..\code\parameter\value\IntegerSQLParameterValue.pas',
  ListSQLParameterValue in '..\..\code\parameter\value\ListSQLParameterValue.pas',
  NullSQLParameterValue in '..\..\code\parameter\value\NullSQLParameterValue.pas',
  SQLParameter in '..\..\code\parameter\SQLParameter.pas',
  SQLParameterValue in '..\..\code\parameter\value\SQLParameterValue.pas',
  StringSQLParameterValue in '..\..\code\parameter\value\StringSQLParameterValue.pas',
  UIntegerSQLParameterValue in '..\..\code\parameter\value\UIntegerSQLParameterValue.pas',
  AscendingSQLSort in '..\..\code\sort\AscendingSQLSort.pas',
  DescendingSQLSort in '..\..\code\sort\DescendingSQLSort.pas',
  NoneSQLSort in '..\..\code\sort\NoneSQLSort.pas',
  SQLSort in '..\..\code\sort\SQLSort.pas',
  SQL in '..\..\code\SQL.pas',
  SQLFilter in '..\..\code\SQLFilter.pas',
  SQLFiltered in '..\..\code\SQLFiltered.pas',
  SQLInjectedFilter in '..\..\code\SQLInjectedFilter.pas',
  BetweenSQLCondition_test in '..\code\condition\BetweenSQLCondition_test.pas',
  EqualSQLCondition_test in '..\code\condition\EqualSQLCondition_test.pas',
  GreaterOrEqualSQLCondition_test in '..\code\condition\GreaterOrEqualSQLCondition_test.pas',
  GreaterSQLCondition_test in '..\code\condition\GreaterSQLCondition_test.pas',
  InSQLCondition_test in '..\code\condition\InSQLCondition_test.pas',
  IsNotNullSQLCondition_test in '..\code\condition\IsNotNullSQLCondition_test.pas',
  IsNullSQLCondition_test in '..\code\condition\IsNullSQLCondition_test.pas',
  JoinedSQLCondition_test in '..\code\condition\JoinedSQLCondition_test.pas',
  LessOrEqualSQLCondition_test in '..\code\condition\LessOrEqualSQLCondition_test.pas',
  LessSQLCondition_test in '..\code\condition\LessSQLCondition_test.pas',
  LikeSQLCondition_test in '..\code\condition\LikeSQLCondition_test.pas',
  NotEqualSQLCondition_test in '..\code\condition\NotEqualSQLCondition_test.pas',
  SQLConditionList_test in '..\code\condition\SQLConditionList_test.pas',
  AndNotSQLJoin_test in '..\code\join\AndNotSQLJoin_test.pas',
  AndSQLJoin_test in '..\code\join\AndSQLJoin_test.pas',
  NoneSQLJoin_test in '..\code\join\NoneSQLJoin_test.pas',
  OrNotSQLJoin_test in '..\code\join\OrNotSQLJoin_test.pas',
  OrSQLJoin_test in '..\code\join\OrSQLJoin_test.pas',
  WhereSQL_test in '..\code\join\WhereSQL_test.pas',
  BooleanSQLParameterValue_test in '..\code\parameter\value\BooleanSQLParameterValue_test.pas',
  DateSQLParameterValue_test in '..\code\parameter\value\DateSQLParameterValue_test.pas',
  DateTimeSQLParameterValue_test in '..\code\parameter\value\DateTimeSQLParameterValue_test.pas',
  ReplaceableSQLParameter_test in '..\code\parameter\ReplaceableSQLParameter_test.pas',
  ReplaceableSQLParameterValue_test in '..\code\parameter\value\ReplaceableSQLParameterValue_test.pas',
  ExtendedFormatSettingValue_test in '..\code\parameter\value\ExtendedFormatSettingValue_test.pas',
  ExtendedSQLParameterValue_test in '..\code\parameter\value\ExtendedSQLParameterValue_test.pas',
  IntegerSQLParameterValue_test in '..\code\parameter\value\IntegerSQLParameterValue_test.pas',
  ListSQLParameterValue_test in '..\code\parameter\value\ListSQLParameterValue_test.pas',
  NullSQLParameterValue_test in '..\code\parameter\value\NullSQLParameterValue_test.pas',
  SQLParameterValue_test in '..\code\parameter\value\SQLParameterValue_test.pas',
  StaticSQLParameter_test in '..\code\parameter\StaticSQLParameter_test.pas',
  StringSQLParameterValue_test in '..\code\parameter\value\StringSQLParameterValue_test.pas',
  UIntegerSQLParameterValue_test in '..\code\parameter\value\UIntegerSQLParameterValue_test.pas',
  AscendingSQLSort_test in '..\code\sort\AscendingSQLSort_test.pas',
  DescendingSQLSort_test in '..\code\sort\DescendingSQLSort_test.pas',
  NoneSQLSort_test in '..\code\sort\NoneSQLSort_test.pas',
  SQL_test in '..\code\SQL_test.pas',
  SQLFilter_test in '..\code\SQLFilter_test.pas',
  SQLFiltered_test in '..\code\SQLFiltered_test.pas',
  SQLInjectedFilter_test in '..\code\SQLInjectedFilter_test.pas',
  Statement in '..\..\code\Statement.pas',
  SQLField in '..\..\code\SQLField.pas',
  StoredText in '..\..\code\store\StoredText.pas',
  ResourceStoredText in '..\..\code\store\ResourceStoredText.pas',
  ResourceStoredText_test in '..\code\store\ResourceStoredText_test.pas',
  StoredSQL in '..\..\code\store\StoredSQL.pas',
  StoredSQL_test in '..\code\store\StoredSQL_test.pas',
  StaticSQLParameter in '..\..\code\parameter\StaticSQLParameter.pas',
  MutableSQLParameter in '..\..\code\parameter\MutableSQLParameter.pas',
  MutableSQLParameter_test in '..\code\parameter\MutableSQLParameter_test.pas',
  DynamicSQLParameter in '..\..\code\parameter\DynamicSQLParameter.pas',
  DynamicSQLParameter_test in '..\code\parameter\DynamicSQLParameter_test.pas',
  RawSQLCondition in '..\..\code\condition\RawSQLCondition.pas',
  RawSQLCondition_test in '..\code\condition\RawSQLCondition_test.pas',
  FileStoredText in '..\..\code\store\FileStoredText.pas',
  FileStoredText_test in '..\code\store\FileStoredText_test.pas';

{R *.RES}

begin
  Run;

end.
