{
  Copyright (c) 2018, Vencejo Software
  Distributed under the terms of the Modified BSD License
  The full license is distributed with this software
}
program test;

uses
  RunTest,
  BetweenSQLCondition in '..\..\code\condition\BetweenSQLCondition.pas',
  EqualSQLCondition in '..\..\code\condition\EqualSQLCondition.pas',
  GreaterOrEqualSQLCondition in '..\..\code\condition\GreaterOrEqualSQLCondition.pas',
  GreaterSQLCondition in '..\..\code\condition\GreaterSQLCondition.pas',
  InSQLCondition in '..\..\code\condition\InSQLCondition.pas',
  IsNotNullSQLCondition in '..\..\code\condition\IsNotNullSQLCondition.pas',
  IsNullSQLCondition in '..\..\code\condition\IsNullSQLCondition.pas',
  JoinedSQLCondition in '..\..\code\condition\JoinedSQLCondition.pas',
  LessOrEqualSQLCondition in '..\..\code\condition\LessOrEqualSQLCondition.pas',
  LessSQLCondition in '..\..\code\condition\LessSQLCondition.pas',
  LikeSQLCondition in '..\..\code\condition\LikeSQLCondition.pas',
  NotEqualSQLCondition in '..\..\code\condition\NotEqualSQLCondition.pas',
  SQLCondition in '..\..\code\condition\SQLCondition.pas',
  AndNotSQLJoin in '..\..\code\join\AndNotSQLJoin.pas',
  AndSQLJoin in '..\..\code\join\AndSQLJoin.pas',
  NoneSQLJoin in '..\..\code\join\NoneSQLJoin.pas',
  OrNotSQLJoin in '..\..\code\join\OrNotSQLJoin.pas',
  OrSQLJoin in '..\..\code\join\OrSQLJoin.pas',
  SQLJoin in '..\..\code\join\SQLJoin.pas',
  WhereSQL in '..\..\code\join\WhereSQL.pas',
  BooleanSQLParameterValue in '..\..\code\parameter\BooleanSQLParameterValue.pas',
  DateSQLParameterValue in '..\..\code\parameter\DateSQLParameterValue.pas',
  DateTimeSQLParameterValue in '..\..\code\parameter\DateTimeSQLParameterValue.pas',
  DynamicSQLParameter in '..\..\code\parameter\DynamicSQLParameter.pas',
  DynamicSQLParameterValue in '..\..\code\parameter\DynamicSQLParameterValue.pas',
  ExtendedFormatSetting in '..\..\code\parameter\ExtendedFormatSetting.pas',
  ExtendedSQLParameterValue in '..\..\code\parameter\ExtendedSQLParameterValue.pas',
  IntegerSQLParameterValue in '..\..\code\parameter\IntegerSQLParameterValue.pas',
  ListSQLParameterValue in '..\..\code\parameter\ListSQLParameterValue.pas',
  NullSQLParameterValue in '..\..\code\parameter\NullSQLParameterValue.pas',
  SQLParameter in '..\..\code\parameter\SQLParameter.pas',
  SQLParameterValue in '..\..\code\parameter\SQLParameterValue.pas',
  StringSQLParameterValue in '..\..\code\parameter\StringSQLParameterValue.pas',
  UIntegerSQLParameterValue in '..\..\code\parameter\UIntegerSQLParameterValue.pas',
  AscendingSQLSort in '..\..\code\sort\AscendingSQLSort.pas',
  DescendingSQLSort in '..\..\code\sort\DescendingSQLSort.pas',
  NoneSQLSort in '..\..\code\sort\NoneSQLSort.pas',
  SQLSort in '..\..\code\sort\SQLSort.pas',
  SQL in '..\..\code\SQL.pas',
  SQLFilter in '..\..\code\SQLFilter.pas',
  SQLFiltered in '..\..\code\SQLFiltered.pas',
  SQLInjectedFilter in '..\..\code\SQLInjectedFilter.pas',
  BetweenSQLCondition_test in '..\code\condition\BetweenSQLCondition_test.pas',
  EqualSQLCondition_test in '..\code\condition\EqualSQLCondition_test.pas',
  GreaterOrEqualSQLCondition_test in '..\code\condition\GreaterOrEqualSQLCondition_test.pas',
  GreaterSQLCondition_test in '..\code\condition\GreaterSQLCondition_test.pas',
  InSQLCondition_test in '..\code\condition\InSQLCondition_test.pas',
  IsNotNullSQLCondition_test in '..\code\condition\IsNotNullSQLCondition_test.pas',
  IsNullSQLCondition_test in '..\code\condition\IsNullSQLCondition_test.pas',
  JoinedSQLCondition_test in '..\code\condition\JoinedSQLCondition_test.pas',
  LessOrEqualSQLCondition_test in '..\code\condition\LessOrEqualSQLCondition_test.pas',
  LessSQLCondition_test in '..\code\condition\LessSQLCondition_test.pas',
  LikeSQLCondition_test in '..\code\condition\LikeSQLCondition_test.pas',
  NotEqualSQLCondition_test in '..\code\condition\NotEqualSQLCondition_test.pas',
  AndNotSQLJoin_test in '..\code\join\AndNotSQLJoin_test.pas',
  AndSQLJoin_test in '..\code\join\AndSQLJoin_test.pas',
  NoneSQLJoin_test in '..\code\join\NoneSQLJoin_test.pas',
  OrNotSQLJoin_test in '..\code\join\OrNotSQLJoin_test.pas',
  OrSQLJoin_test in '..\code\join\OrSQLJoin_test.pas',
  WhereSQL_test in '..\code\join\WhereSQL_test.pas',
  SymbolListMock in '..\code\mock\SymbolListMock.pas',
  BooleanSQLParameterValue_test in '..\code\parameter\BooleanSQLParameterValue_test.pas',
  DateSQLParameterValue_test in '..\code\parameter\DateSQLParameterValue_test.pas',
  DateTimeSQLParameterValue_test in '..\code\parameter\DateTimeSQLParameterValue_test.pas',
  DynamicSQLParameterValue_test in '..\code\parameter\DynamicSQLParameterValue_test.pas',
  ExtendedFormatSettingValue_test in '..\code\parameter\ExtendedFormatSettingValue_test.pas',
  ExtendedSQLParameterValue_test in '..\code\parameter\ExtendedSQLParameterValue_test.pas',
  IntegerSQLParameterValue_test in '..\code\parameter\IntegerSQLParameterValue_test.pas',
  ListSQLParameterValue_test in '..\code\parameter\ListSQLParameterValue_test.pas',
  NullSQLParameterValue_test in '..\code\parameter\NullSQLParameterValue_test.pas',
  RawSQLParameterValue_test in '..\code\parameter\RawSQLParameterValue_test.pas',
  SQLParameter_test in '..\code\parameter\SQLParameter_test.pas',
  StringSQLParameterValue_test in '..\code\parameter\StringSQLParameterValue_test.pas',
  UIntegerSQLParameterValue_test in '..\code\parameter\UIntegerSQLParameterValue_test.pas',
  AscendingSQLSort_test in '..\code\sort\AscendingSQLSort_test.pas',
  DescendingSQLSort_test in '..\code\sort\DescendingSQLSort_test.pas',
  NoneSQLSort_test in '..\code\sort\NoneSQLSort_test.pas',
  SQL_test in '..\code\SQL_test.pas',
  SQLFilter_test in '..\code\SQLFilter_test.pas',
  SQLFiltered_test in '..\code\SQLFiltered_test.pas',
  SQLInjectedFilter_test in '..\code\SQLInjectedFilter_test.pas',
  SingleSQLCondition in '..\..\code\condition\SingleSQLCondition.pas',
  DynamicSQLParameter_test in '..\code\parameter\DynamicSQLParameter_test.pas',
  SQLConditionList_test in '..\code\condition\SQLConditionList_test.pas';

{R *.RES}

begin
  Run;

end.
